# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'talker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.0'
  pod 'Kakapo', '~> 2.1.0'

  pod 'SwiftyJSON', '~> 3.0'
  pod 'Alamofire', '~> 4.0'

  pod 'Haneke', '~> 1.0'
  pod 'HCSStarRatingView', '~> 1.4.5'
  
  pod 'TalkerFramework', :git =>'https://github.com/mathiasAichinger/talker-framework.git'
end
