# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'talker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 3.0'
  pod 'Kakapo', '~> 2.1.0'

  pod 'SwiftyJSON', '~> 3.0'
  pod 'Alamofire', '~> 4.0'

end
